### ISSUE TITLE
Full trace is wrong

### ISSUE THREAD

**Issue by xnnkmd** [stuisme/jasmine-pretty-html-reporter#3]
The overview of passed and failed tests show the correct first line of failure in source code with sourcemaps enabled - but if I click on an error the details window does not show the entire trace - it leaves out the source code line of the test.

**Comment by stuisme** [comment]
@xnnkmd anyway you can send a screenshot of the dialog?

**Comment by stuisme** [comment]
Hope this helps

**Comment by xnnkmd** [comment]
Yes, very helpful. Better. The only problem now is that the stacktrace shows too much. In the example below, the first 6 lines are showing jasmine internals and are irrelevant for the test. 
P.S. Your overview page does not have this problem as it one shows one line, which is the relevant source code line.
P.S.2. I noticed the same problem in some other report npms. Some reports like for instance "jasmine-console-reporter" does stack filtering correctly, while others like "jasmine-reporters" has the same issue.

![trace](https://cloud.githubusercontent.com/assets/26216976/23785734/6cac0134-0569-11e7-83d1-051bb362cd84.PNG)

**Comment by stuisme** [comment]
When jasmine reports the error it gives the whole stack trace which is in the dialog. What you see on the overview the the best guess for which line in the whole stack trace is the local project and not a npm package or a node internal thing. This concept is called suspectLine in this reporter.

Since suspectLine is a guess, the idea was to show the full stack in the dialog, in the case it does not guess the line correctly. I was planning on enhancing the dialog to highlight the suspectLine.

**Comment by stuisme** [comment]
Added a feature that will highlight the suspect line in the dialog.

**Comment by xnnkmd** [comment]
Thanks - works fine now with highlightning. Great!
